name: Java CI with Maven

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: git_actions
      GIT_AUTHOR_EMAIL: vbeliakou@protonmail.com
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Prepare release
        run: mvn release:prepare --batch-mode
      - name: Checkout release
        run: git checkout @~1
      - name: Publish
        run: mvn deploy