name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Prepare release
        run: mvn release:prepare --batch-mode
      - name: Checkout release
        run: git checkout @~1
      - name: Publish
        run: mvn deploy